### ISSUE TITLE
[Suggestion] Cost estimation in the file browser

### ISSUE THREAD

**Issue by Mavyre** [malnvenshorn/OctoPrint-CostEstimation#6]
Hello,

I think the issue is self-explainatory... It would be great to have the cost estimation without having to turn on printer, and load the model. Also, see with PrintHistory author we can see the cost of previous prints (with statistics?)? I'll post an issue on its respository also.

Thanks for this really great plugin!

**Comment by malnvenshorn** [comment]
I'm not convinced that it would be a great idea to put the cost estimation inside the info dropdown of each model in the file browser. The reason is that the cost depends on the selected filament and might vary a lot if you use different materials and/or different vendors. If you can't load the model (e.g. if a print is currently running) and you don't want the model printed with the same material the estimated cost would be worthless for you. If you don't want to turn on your printer to check the cost for a model you could use the virtual printer plugin and connect to the virtual port. Then you can load the model and check the estimated cost.

Coming to the print history. First I don't know the PrintHistory plugin and what features it has. But I'm in the process of moving the filament manager part into a separate [plugin](https://github.com/malnvenshorn/OctoPrint-FilamentManager) which provides an api to access the data, so every plugin could use this to provide a history of the costs of previous prints.

**Comment by Mavyre** [comment]
Just got your new filament manager plugin. I'm writting an issue right now on PrintHistory's repository to let them interface it with yours.

Thank you for all your work!

**Comment by JoschaMiddendorf** [comment]
If OctoPrint-FilamentManager Plugin could choose the right spool automatically, by adding a Spool indicating comment to the G-Code, the cost of a print could also be determined without selecting a spool Manually.
Therefore, the price could be displayed in files section.

Would that be a nice idea to implement that?
For me, that would be a game changer because i regularly need to determine costs prior to a print for quotations, even while a current print is running.

[https://github.com/malnvenshorn/OctoPrint-FilamentManager/issues/151](url)
